### PR TITLE
Fixed initialisation and warnings

### PR DESCRIPTION
**Pull request by Naatan**
Just tried the addon this morning, unfortunately it wasn't working. Seems it was still initialising too soon (this is why settimeout is bad, it's a shot in the dark). While fixing the issue I also came across a XUL warning about writing straight to the statusbarpanel element, which I fixed as well.

The rest is some minor cleanup. Eg. only bind the rest of the listeners once the OnLoad is fired to ensure they don't fire too early.

I really like this addon, honestly it's something we should have done ages ago. Just working on fixing some minor issues I get a boatload of ideas on what else we could do. Are you interested in developing it further or were you simply looking to address a single use-case?

### CODE REVIEW

**Comment by ervumlens** [comment]
@Naatan Hey, log an issue, pal. :wink:

Good work, @neurobashing .

**Comment by neurobashing** [comment]
I'd like to develop it further, eg it should list all the branches on click and let you switch between them.

**Comment by neurobashing** [comment]
it also doesn't handle errors AT ALL, which was what I planned to do today before life intruded ...

**Comment by Naatan** [comment]
Weekends never go the way you plan, thats why I like weekdays :p

Glad you intend to develop it further :) I look forward to your updates.

@ervumlens I wanted to use it too badly :p

**Comment by Defman21** [comment]
@neurobashing if you don't mind, please create a new release that contains the fix.

**Pull request merged**
